services:
  sumo:
    image: jamrow/sumo:${IMAGE_TAG}
    depends_on:
      - redis
    networks:
      - frontend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  websocket:
    image: jamrow/websocket:${IMAGE_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sumo
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    labels:
      - "com.example.redeploy=5"

  redis:
    image: redis:7
    networks:
      - frontend

networks:
  frontend:
    external: true