services:
  sumo:
    image: jamrow/sumo:${IMAGE_TAG}
    depends_on:
      - redis
    networks:
      - frontend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      placement:
        constraints:
          - node.hostname == ubuntu-s-1vcpu-1gb-nyc1-01
      replicas: 1
      restart_policy:
        condition: on-failure

  websocket:
    image: jamrow/websocket:${IMAGE_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sumo
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.http.routers.sumo-https.rule=Host(`cars.shmaxes.com/ws`)"
        - "traefik.http.routers.sumo-https.service=websocket"
        - "traefik.http.services.sumo-service.loadbalancer.server.port=8000"

  redis:
    image: redis:7
    networks:
      - frontend
    expose:
      - "6379"

networks:
  frontend:
    external: true