
services:
  sumo:
    image: jamrow/sumo:latest
    depends_on:
      - redis
    networks:
      - simnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  websocket:
    image: jamrow/websocket:latest
    ports:
      - "80:80"
    depends_on:
      - redis
      - sumo
    networks:
      - simnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - simnet

networks:
  simnet:
