services:
  sumo:
    image: jamrow/sumo:latest # Use latest directly
    depends_on:
      - redis
    networks:
      - simnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  websocket:
    image: jamrow/websocket:latest # Use latest directly
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sumo
    networks:
      - simnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    labels:
      - "com.example.redeploy=4"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - simnet

networks:
  simnet: