
services:
  sumo:
    image: jamrow/sumo:latest
    depends_on:
      - redis
    networks:
      - simnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  websocket:
    image: jamrow/websocket:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sumo
    networks:
      - simnet
    deploy:
      replicas: 1
      restart_policy:
        #condition: none
        condition: any
    labels:
      - "com.example.redeploy=1"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - simnet

networks:
  simnet:
  
