name: Deploy to Droplet

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 159.223.108.202
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/sumo
            git pull
            docker build -t jamrow/websocket:latest ./websocket
            docker build -t jamrow/sumo:latest ./sumo
            docker stack deploy -c docker-compose.yml sumo_stack
            docker service update --force sumo_stack_sumo
            docker service update --force sumo_stack_websocket
