name: Deploy to Droplet

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            script: |
              GIT_COMMIT=$(git rev-parse --short HEAD)
              docker build -t jamrow/websocket:${GIT_COMMIT} -t jamrow/websocket:latest ./websocket
              docker build -t jamrow/sumo:${GIT_COMMIT} -t jamrow/sumo:latest ./sumo
              docker push jamrow/websocket:${GIT_COMMIT} # <-- Pushing the commit tag
              docker push jamrow/websocket:latest
              docker push jamrow/sumo:${GIT_COMMIT} # <-- Pushing the commit tag
              docker push jamrow/sumo:latest
              # ...
              IMAGE_TAG=${GIT_COMMIT} docker stack deploy -c docker-compose.yml sumo_stack