name: Deploy to Droplet

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            script: |
              cd /root/sumo # Or wherever your repo is cloned
              git pull
              git lfs pull
              # No need for GIT_COMMIT in environment variable if always using latest for deploy
              docker build -t jamrow/websocket:latest ./websocket
              docker build -t jamrow/sumo:latest ./sumo
              docker push jamrow/websocket:latest
              docker push jamrow/sumo:latest
              docker system prune -f # Cleans up runner's docker resources
              docker stack deploy -c docker-compose.yml sumo_stack # No IMAGE_TAG variable needed